name: "Terraform"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: hashicorp/setup-terraform@v1
      
      - name: Format
        working-directory: infra
        run: terraform fmt -check

      - name: Init
        working-directory: infra
        run: terraform init

      - name: Plan
        working-directory: infra
        run: terraform plan
        env:
          TF_AWS_REGION: eu-west-2
          TF_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_DOMAIN_NAME: nathanshaw.uk

      - name: Apply
        if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
        working-directory: infra
        run: terraform apply
        env:
          TF_AWS_REGION: eu-west-2
          TF_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          TF_DOMAIN_NAME: nathanshaw.uk
