name: "Terraform"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: hashicorp/setup-terraform@v1

      - name: Setup AWS Credentials
        working-directory: infra
        run: |
          sudo echo -e "[default]\n\
            \raws_access_key_id=$ACCESS_ID\n\
            \raws_secret_access_key=$SECRET_KEY" \
            > aws-credentials
        env:
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Format
        working-directory: infra
        run: terraform fmt -check

      - name: Init
        working-directory: infra
        run: |
          cat aws-credentials
          terraform init

      - name: Plan
        working-directory: infra
        run: terraform plan
        timeout-minutes: 1
        env:
          TF_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

      - name: Apply
        if: (github.ref == 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
        working-directory: infra
        timeout-minutes: 5
        run: terraform apply -auto-approve
        env:
          TF_AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          TF_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
